# Generated by Django 2.2.28 on 2022-11-12 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agence',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom_agence', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom_personnel', models.CharField(max_length=32)),
                ('prenom_personnel', models.CharField(max_length=32)),
                ('phone_personnel', models.CharField(max_length=32)),
                ('sexe', models.CharField(max_length=10)),
                ('cni', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom_commune', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Mutuelle',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom_mutuelle', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom_personnel', models.CharField(max_length=32)),
                ('prenom_personnel', models.CharField(max_length=32)),
                ('phone_personnel', models.CharField(max_length=32)),
                ('sexe', models.CharField(max_length=10)),
                ('cni', models.CharField(max_length=32)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Agence')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom_produit', models.CharField(max_length=40)),
                ('prix_achat', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom_province', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom_zone', models.CharField(max_length=32)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Commune')),
            ],
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('valeur_total', models.IntegerField(default=0)),
                ('payer', models.IntegerField(default=0)),
                ('a_payer', models.IntegerField(default=0)),
                ('paid', models.BooleanField(default=True)),
                ('date_vente', models.DateTimeField(auto_now=True)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Agence')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Client')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Personnel')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Produit')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom_stock', models.CharField(max_length=32)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Agence')),
            ],
        ),
        migrations.CreateModel(
            name='Quartier',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom_quartier', models.CharField(max_length=32)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Zone')),
            ],
        ),
        migrations.AddField(
            model_name='produit',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Stock'),
        ),
        migrations.CreateModel(
            name='Dette',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_paye', models.DateTimeField(blank=True, null=True)),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Vente')),
            ],
        ),
        migrations.AddField(
            model_name='commune',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Province'),
        ),
        migrations.AddField(
            model_name='agence',
            name='quartier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Quartier'),
        ),
    ]
