# Generated by Django 2.2.28 on 2022-11-12 12:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_produit_dateexpiration'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='num_serie',
            field=models.CharField(default=django.utils.timezone.now, max_length=60),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='produit',
            unique_together={('nom_produit', 'num_serie')},
        ),
    ]
